# Pre-commit hooks configuration
# https://pre-commit.com/

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=88']

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black']

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=88',
          '--extend-ignore=E203,W503,D100,D101,D102,D103,D104',
          '--exclude=.git,__pycache__,build,dist,*.egg-info,.old,._*'
        ]
        additional_dependencies: [
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-simplify',
        ]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--install-types', '--non-interactive']
        additional_dependencies: [
          'types-requests',
          'types-setuptools',
          'pandas-stubs',
        ]
        exclude: ^(tests/|docs/|setup\.py)

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ['-ll', '-i', '-r']
        exclude: ^tests/

  # Docstring formatting
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D203,D204,D213,D215,D400,D401,D404,D406,D407,D408,D409,D413']
        exclude: ^(tests/|setup\.py|docs/)

  # YAML formatting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['--format', 'parsable', '--strict']

  # Markdown formatting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  # Spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['--skip=*.svg,*.json,*.lock', '--ignore-words-list=mngs,ywatanabe']

  # Jupyter notebook cleaning
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # Custom hooks
  - repo: local
    hooks:
      - id: no-commit-to-branch
        name: Don't commit to main/master
        entry: bash -c 'if [[ $(git symbolic-ref --short HEAD) =~ ^(main|master)$ ]]; then echo "Direct commits to main/master branch are not allowed. Please use a feature branch."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true

      - id: tests-pass
        name: Ensure tests pass
        entry: bash -c 'python -m pytest tests/ -x --tb=short || (echo "Tests must pass before commit" && exit 1)'
        language: system
        pass_filenames: false
        stages: [push]

# Configuration
default_language_version:
  python: python3.10

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [tests-pass]  # Don't run tests in CI
  submodules: false