# Timestamp: "2025-05-03 16:07:25 (ywatanabe)"
# File: /home/ywatanabe/proj/mngs_repo/.github/workflows/install-pypi-latest.yml

name: install-pypi-latest

on:
  push:
    branches:
      - main      
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: install-pypi-latest
      run: |
          pip install -U pip        
          pip install mngs
          python ./tests/custom/test_mngs_run.py

# EOF