name: Comprehensive Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run comprehensive tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-all-modules:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [gen, io, plt, dsp, stats, pd, ai, nn, db]
    
    name: Test ${{ matrix.module }} module
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libhdf5-dev \
          libopenblas-dev \
          liblapack-dev \
          gfortran \
          ffmpeg \
          graphviz
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-timeout
    
    - name: Run ${{ matrix.module }} tests
      run: |
        python -m pytest tests/mngs/${{ matrix.module }} -v \
          --cov=src/mngs/${{ matrix.module }} \
          --cov-report=xml:coverage-${{ matrix.module }}.xml \
          --timeout=300
    
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.module }}
        path: coverage-${{ matrix.module }}.xml

  test-integration:
    runs-on: ubuntu-latest
    needs: test-all-modules
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-timeout
    
    - name: Run integration tests
      run: |
        python -m pytest tests/integration -v --timeout=600

  test-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert
    
    - name: Test notebooks
      run: |
        # Convert notebooks to scripts and test execution
        find examples -name "*.ipynb" -exec jupyter nbconvert --to script {} \;
        find examples -name "*.py" -exec python {} \;

  coverage-report:
    needs: test-all-modules
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all coverage reports
      uses: actions/download-artifact@v3
      with:
        path: coverage-reports
    
    - name: Combine coverage reports
      run: |
        pip install coverage
        coverage combine coverage-reports/*/coverage-*.xml
        coverage report
        coverage html
    
    - name: Upload combined coverage
      uses: actions/upload-artifact@v3
      with:
        name: combined-coverage-report
        path: htmlcov/